# Generated by Django 4.2.25 on 2025-11-10 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房间名称')),
                ('location', models.CharField(help_text='例如：3楼301室', max_length=200, verbose_name='位置')),
                ('capacity', models.IntegerField(help_text='最多容纳人数', verbose_name='容量')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('remarks', models.TextField(blank=True, verbose_name='备注信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '会议室',
                'verbose_name_plural': '会议室',
                'db_table': 'bookings_meeting_room',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_advance_days', models.IntegerField(default=30, verbose_name='最大提前预约天数')),
                ('min_duration_minutes', models.IntegerField(default=15, verbose_name='最短预约时长(分钟)')),
                ('max_duration_hours', models.IntegerField(default=8, verbose_name='最长预约时长(小时)')),
                ('allow_weekend_booking', models.BooleanField(default=False, verbose_name='允许周末预约')),
                ('work_start_time', models.TimeField(default='09:00', verbose_name='工作开始时间')),
                ('work_end_time', models.TimeField(default='18:00', verbose_name='工作结束时间')),
                ('require_approval', models.BooleanField(default=False, verbose_name='需要审批')),
                ('auto_approval', models.BooleanField(default=False, verbose_name='自动审批')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_config', to='companies.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '预约配置',
                'verbose_name_plural': '预约配置',
                'db_table': 'bookings_reservation_config',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='预约主题')),
                ('description', models.TextField(blank=True, verbose_name='会议描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('participant_count', models.IntegerField(blank=True, help_text='预计参与会议的人数', null=True, verbose_name='参与人数')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('completed', '已完成'), ('in_use', '使用中'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='预约公司')),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.meetingroom', verbose_name='会议室')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_meetings', to=settings.AUTH_USER_MODEL, verbose_name='参会人员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'bookings_reservation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'start_time', 'end_time'], name='bookings_re_company_c25047_idx'), models.Index(fields=['meeting_room', 'start_time', 'end_time'], name='bookings_re_meeting_62c20c_idx'), models.Index(fields=['user', 'start_time'], name='bookings_re_user_id_175635_idx'), models.Index(fields=['status', 'start_time'], name='bookings_re_status_66f375_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['company', 'is_available'], name='bookings_me_company_8399b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingroom',
            unique_together={('company', 'name')},
        ),
    ]
